export const propertyType = {
  name: 'property',
  title: 'Property',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'status',
      title: 'Listing Status',
      type: 'string',
      options: {
        list: [
          { title: 'Available', value: 'available' },
          { title: 'Sold', value: 'sold' },
          { title: 'Rented', value: 'rented' },
          { title: 'Unavailable', value: 'unavailable' },
        ],
      },
      initialValue: 'available',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'isFeatured',
      title: 'Is Featured?',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'purpose',
      title: 'Purpose',
      type: 'string',
      options: { list: ['Sale', 'Rent'] },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'type',
      title: 'Property Type',
      type: 'reference',
      to: [{ type: 'propertyCategory' }],
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'location',
      title: 'Location',
      type: 'reference',
      to: [{ type: 'location' }],
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'developer',
      title: 'Developer',
      type: 'reference',
      to: [{ type: 'developer' }],
    },
    {
      name: 'price',
      title: 'Display Price',
      type: 'string',
      description: 'e.g. ₹ 4.5 Cr',
    },
    {
      name: 'priceValue',
      title: 'Numeric Price Value',
      type: 'number',
      description: 'Used for filtering/sorting',
    },
    {
      name: 'configuration',
      title: 'Configuration (BHK)',
      type: 'string',
    },
    {
      name: 'area',
      title: 'Area (Display)',
      type: 'string',
      description: 'e.g. 3500 sqft',
    },
    {
      name: 'areaValue',
      title: 'Numeric Area Value',
      type: 'number',
    },
    {
      name: 'furnishing',
      title: 'Furnishing',
      type: 'string',
      options: { list: ['Furnished', 'Semi-furnished', 'Unfurnished'] },
    },
    {
      name: 'facing',
      title: 'Facing',
      type: 'string',
      options: { list: ['East', 'North', 'South', 'West', 'North-East', 'North-West', 'South-East', 'South-West'] },
    },
    {
      name: 'projectStatus',
      title: 'Project Status',
      type: 'string',
      options: { list: ['Under Construction', 'Ready Homes', 'New Launch', 'Resale'] },
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text',
    },
    {
      name: 'amenities',
      title: 'Amenities',
      type: 'array',
      of: [{ type: 'string' }],
    },
    {
      name: 'images',
      title: 'Images',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      validation: (Rule: any) => Rule.required().min(1),
    },
  ],
}
